
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/veticore}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  sql:
    init:
      mode: NEVER
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
server:
  port: ${PORT:8080}
  error:
    include-message: always
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
jwt:
  public:
    key: classpath:authz.pub
  private:
    key: classpath:authz.pem
